"""Feeding the checked-in Visual Studio smoke test projects.

``smoke/vs/msvc-<toolset>/`` holds a real ``.sln`` plus a ``BoostSmoke.vcxproj``
and ``BoostSmokePython.vcxproj`` for every toolset in ``build.toml``, so
someone can open one in Visual Studio and build the smoke program the way a
consumer of these binaries would, instead of through the direct ``cl.exe``
invocation the rest of :mod:`boostwin.smoke` uses.

Those projects do not know where a build staged its libraries -- that varies
by build root, release version and configuration.  This module writes a
``.props`` file into ``generated/`` next to them, named after the
Configuration|Platform pair it belongs to, which is what the vcxproj files
import to fill in ``BoostIncludeDir``, ``BoostLibDir`` and friends.  It is
regenerated on every ``boostwin test`` run, and is also what lets that same
command drive the projects with ``msbuild`` for the "msbuild"/"msbuild-python"
checks alongside the existing ones.
"""
from pathlib import Path

from .msvc import host_arch
from .util import fail

# PlatformToolset token MSBuild expects for each toolset. Kept separate from
# Toolset.name since it is a Visual Studio spelling, not ours.
PLATFORM_TOOLSET = {
    "14.1": "v141",
    "14.2": "v142",
    "14.3": "v143",
    "14.5": "v145",
}

PLATFORM_NAME = {"32": "Win32", "64": "x64", "arm64": "ARM64"}

# Suffix the checked-in vcxproj files use for each link/runtime-link
# combination, appended to the capitalised variant name -- must match
# smoke/vs/*/BoostSmoke*.vcxproj's <ProjectConfiguration> entries exactly.
_CONFIGURATION_SUFFIX = {
    ("shared", "shared"): "",
    ("static", "shared"): "-Static",
    ("static", "static"): "-StaticRuntime",
}


def platform_toolset(toolset):
    try:
        return PLATFORM_TOOLSET[toolset.name]
    except KeyError:
        fail("no Visual Studio PlatformToolset is known for msvc-{}; add it "
             "to boostwin.vsproj.PLATFORM_TOOLSET (and generate a project "
             "for it under smoke/vs/)".format(toolset.name))


def configuration_name(build_config):
    """The vcxproj ``Configuration`` name for this build, e.g. ``Debug-Static``."""
    try:
        suffix = _CONFIGURATION_SUFFIX[(build_config.link,
                                        build_config.runtime_link)]
    except KeyError:
        fail("no Visual Studio configuration is defined for link={} "
             "runtime-link={}".format(build_config.link,
                                      build_config.runtime_link))
    return build_config.variant.capitalize() + suffix


def platform_name(build_config):
    """The vcxproj ``Platform`` name for this build, e.g. ``x64``."""
    try:
        return PLATFORM_NAME[build_config.arch.key]
    except KeyError:
        fail("no Visual Studio platform is defined for architecture {!r}; "
             "add it to boostwin.vsproj.PLATFORM_NAME".format(
                 build_config.arch.key))


def project_dir(config, toolset):
    """Where the checked-in .sln/.vcxproj for this toolset live."""
    return config.root / "smoke" / "vs" / ("msvc-" + toolset.name)


def solution_path(config, toolset):
    return project_dir(config, toolset) / "BoostSmoke.sln"


def vcxproj_path(config, toolset):
    return project_dir(config, toolset) / "BoostSmoke.vcxproj"


def python_vcxproj_path(config, toolset):
    return project_dir(config, toolset) / "BoostSmokePython.vcxproj"


def has_project(config, build_config):
    """Whether this configuration's toolset has a checked-in VS project."""
    return (build_config.toolset.name in PLATFORM_TOOLSET
            and vcxproj_path(config, build_config.toolset).exists())


def props_path(config, build_config):
    """Where ``write_props`` writes/looks for this configuration's .props."""
    name = "{}-{}.props".format(configuration_name(build_config),
                                platform_name(build_config))
    return project_dir(config, build_config.toolset) / "generated" / name


def output_exe(config, build_config):
    return (project_dir(config, build_config.toolset)
            / platform_name(build_config) / configuration_name(build_config)
            / "BoostSmoke.exe")


def _win_path(path):
    """A Windows-style path string, regardless of the OS this runs on."""
    return str(path).replace("/", "\\")


_PROPS_TEMPLATE = """<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <!-- Generated by boostwin.vsproj.write_props; do not edit by hand. -->
  <PropertyGroup Label="BoostwinPaths">
{properties}
  </PropertyGroup>
</Project>
"""


def write_props(workspace, build_config):
    """Write the .props file this configuration's vcxproj imports.

    Supplies the include/library directories for Boost and (when the
    dependency is unpacked) Python, plus the exact staged file name for any
    library Boost does not auto-link -- ``boost_charconv``, at the moment --
    since a vcxproj cannot glob for it the way
    :func:`boostwin.smoke.extra_link_libraries` does.
    """
    # Imported here, not at module level: boostwin.smoke imports this module
    # to drive msbuild, so a top level import the other way round would be
    # circular.
    from . import smoke as smoke_module

    config = workspace.config
    path = props_path(config, build_config)
    path.parent.mkdir(parents=True, exist_ok=True)

    entries = [
        ("BoostIncludeDir", workspace.source),
        ("BoostLibDir", workspace.stage_lib(build_config)),
    ]
    python_root = workspace.python_root(build_config.arch)
    if python_root.is_dir():
        entries.append(("PythonIncludeDir", python_root / "include"))
        entries.append(("PythonLibDir", python_root / "libs"))
        entries.append(("PythonExe", python_root / "python.exe"))

    extra, _problems = smoke_module.extra_link_libraries(
        workspace.stage_lib(build_config), config.smoke.extra_link_libs)
    if extra:
        entries.append(("BoostExtraLibs",
                        ";".join(_win_path(p) for p in extra)))

    properties = "\n".join(
        "    <{0}>{1}</{0}>".format(name, _win_path(value))
        for name, value in entries)
    path.write_text(_PROPS_TEMPLATE.format(properties=properties),
                    encoding="utf-8")
    return path


# MSBuild ships one build per host architecture in its own subdirectory of
# Bin, with the 32 bit x86 one at the top.  Taking the host's own first is
# what keeps an Arm64 runner off the emulated x64 copy: that one works, but
# it runs the whole smoke build through emulation.
_MSBUILD_HOST_DIR = {"amd64": "amd64", "arm64": "arm64"}


def find_msbuild(install_path):
    """Locate MSBuild.exe inside a Visual Studio installation."""
    base = Path(install_path) / "MSBuild" / "Current" / "Bin"
    host = _MSBUILD_HOST_DIR.get(host_arch(), "amd64")
    for candidate in (base / host / "MSBuild.exe",
                      base / "amd64" / "MSBuild.exe",
                      base / "MSBuild.exe"):
        if candidate.exists():
            return candidate
    fail("MSBuild.exe not found under {}".format(base))
